# Generated by Django 4.2.5 on 2023-09-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "timezone",
                    models.CharField(max_length=50, null=True, verbose_name="Timezone"),
                ),
                (
                    "some_bool",
                    models.BooleanField(default=False, verbose_name="Some Bool"),
                ),
            ],
        ),
    ]
